name: Build Changed Modules

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Determine changed modules
        id: changed-modules
        run: |
          # Get a list of changed files
          changed_files=$(git diff --name-only origin/main HEAD)
          
          # Identify Modified Modules
          changed_modules=""
          for file in $changed_files; do
            module=$(echo $file | cut -d '/' -f1)
            if [[ $module != "." && $module != "" && -d $module ]]; then
              if [[ ! " ${changed_modules[@]} " =~ " ${module} " ]]; then
                changed_modules+="$module,"
              fi
            fi
          done
          
          # Remove the last comma and print the result
          changed_modules=${changed_modules%,}
          echo "Changed modules: $changed_modules"
          
          # Set output for later use
          echo "::set-output name=modules::$changed_modules"

      - name: Build changed modules
        if: steps.changed-modules.outputs.modules != ''
        run: |
          mvn -pl ${{ steps.changed-modules.outputs.modules }} -am verify --no-transfer-progress
