name: Build Projects

on:
  pull_request:

jobs:
  build-hw01-xml-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project 1
        run: |
          cd hw01-xml-config
          mvn verify --no-transfer-progress
